### ISSUE TITLE
https://api.joinmastodon.org/update-check serves HTTP 500 Errors

### ISSUE THREAD

**Issue by chriscroome** [mastodon/joinmastodon#803]
The URL `https://api.joinmastodon.org/update-check` serves HTTP 500 errors, in the past it served JSON with the status code 200, is this due to a bug or problem or is this intentional?

**Comment by renchap** [comment]
This endpoint is expected to have a `version` argument. For example https://api.joinmastodon.org/update-check?version=4.3.0 is working.

I am not sure it ever worked without arguments, can you please provide more details on the request you are making?

**Comment by andypiper** [comment]
Ah, it looks like you're possibly (?) [trying to send just a version number without a parameter](https://git.coop/webarch/mastodon/-/blob/main/tasks/checks.yml#L269)? 

The version check API was [introduced](https://github.com/mastodon/mastodon/blob/d6349c0e9aa93c3d9f70dafb26cf792e874022bf/CHANGELOG.md?plain=1#L625) in the last couple of years so that admins could be alerted to available upgrades, and I'm not sure that it was formally documented for external / non-core-app usage. We should consider whether that is required here.

**Comment by chriscroome** [comment]
Thanks @andypiper and @renchap and very sorry for wasting your time, it was a missing `version=` in the URL that caused the issue, not a problem with the service. 🙄

**Comment by andypiper** [comment]
Thanks for clarifying, good to know!
